name: Merge DEV to PROD

on:
  push:
    branches:
      - DEV

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge DEV to PROD
      run: |
        git checkout PROD
        git merge DEV

    - name: Push changes
      uses: ad-m/github-push-action@v1
      with:
        branch: PROD
        force: true
