name: Merge Code

on:
  push:
    branches:
      - DEV

jobs:
  merge_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge Code
        run: git merge origin/DEV
      - name: Push
        run: git push origin PROD