name: PRs to master
on: 
  pull_request:
    branches: DEV
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "baighakeemyar.cloudlem@gmail.com"
          git config --local user.name "HakeemYB"
    - name: Merge DEV back to PROD
      run: |
          git fetch --unshallow
          git checkout PROD
          git pull
          git merge --no-ff DEV -m "Auto-merge DEV back to PROD"
          git push