name: Merge Code to PROD

on:
  push:
    branches:
      - DEV

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to PROD
      run: |
        git checkout PROD
        git merge DEV
        git push origin PROD
