name: Merge code to PROD

on:
  push:
    branches:
      - DEV

jobs:
  merge_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge PROD
        run: git merge origin/PROD
      - name: Push changes
        run: git push origin DEV
